### ISSUE TITLE
No Oauth Authentication

### ISSUE THREAD

**Issue by DevSatpathy** [HackIllinois/api#334]
In it's current state, the Hackillinois API requires Oauth from Github, Google, or Linkedin to function. This limits accessibility to people with none of those accounts (Situation: Incoming freshman at UIUC get Outlook accounts, not Google Apps, and may not have made Linkedin/Githubs, especially if not in CS). As a result, the Hack API should offer some framework for registrations with a custom authentication (username/password) that can be stored securely in the database, as an optional way to get the authorization JWT.

**Comment by beyerch** [comment]
Are you thinking any arbitrary username or do you want to possibly tie it to an illinois account?  I assume email address is already being captured so that could be used as the login/account?  Should this be limited to *@illinois.edu ?

**Comment by DevSatpathy** [comment]
So this would have to tie into the user service, which is what gives a JWT that is necessary for all other api requests. The user service provisions a UUID (usually github+UUID_String or google+UUID_String). The corresponding JSON struct that must be initialized is:
{
    "id": "github09829234",
    "username": "ExampleUsername",
    "firstName": "ExampleFirstName",
    "lastName": "ExampleLastName",
    "email": "examplemail@gmail.com"
}

So while this could be used for an oAuth check using Illinois emails, that would be a separate issue/PR, since we want some sort of basic username/password in a table that can be hashed/compared. Probably need to decide on a convention for the username to populate the struct (simply concatenating first+lastname is a viable option), and then let people login with their email and password.
I think the goal is to make the API more universally deployable, so other organizations and groups can deploy its services to run their own events at scale.

**Comment by beyerch** [comment]
firstname + lastname is probably not safe enough, especially given your point about opening this up for large audience.  It would definitely be possible to have an overlap for common names.  Even adding middle initial could have overlap.  Email is generally safe as it would be unique within an organization.  

We could also just allow arbitrary choice of username as well.  My thought was that if we were already going to capture the email anyway, it would be slightly more efficient since we're already collecting it and it would be unqiue, etc.  Emails are not 'bullet proof' either since people do change email addresses over time and that could be problematic.

If we add our own system, I assume other things that need to be considered are:
   - Forgotten logins / Passwords
   - Lock outs 
   - "Spam" Accounts / captcha"
   - Assume some sort of email / account verification on signup.  

Some of this may already be in place?  (e.g. email / verification email)

**Comment by DevSatpathy** [comment]
Yeah I wouldn't be too worried about changing emails, especially because registration for events like HackIllinois and similar events that this is designed for start a month before the actual event, and the API deployment is only designed to be up for the span of a couple months.

Good point on the captcha, and the forgotten logins/passwords, I sort of forgot about those points. But yes, an email is sent to the user upon successful registration, this can also perhaps serve as verification.
