### ISSUE TITLE
Enumerate roles

### ISSUE THREAD

**Issue by YashoSharma** [HackIllinois/api#37]
Create enum for roles and use that instead of string representations.

**Comment by Advai** [comment]
So, just to make sure I understand the problem, I need to make an enum in [this function](https://github.com/HackIllinois/api/blob/4c7d2590d9d7885742246f51a6c298e7cc7c1727/gateway/utils/jwt.go#L48) which will contain the "Admin", "Attendee", "Applicant" and "Mentor" roles. Then I would need to go through and replace any role strings with the enum type. Did I miss any roles?

**Comment by PradyumnaShome** [comment]
These roles are the roles I know of: Admin, Attendee, Applicant, Mentor, and User.
The enum should be in a place with the minimum scope such that it is accessible anywhere where role checking / assigning takes place. Being declared in that function, will prevent it from being accessible in the gateway. I would probably put it in `commons` since it used both by the Auth middleware and the gateway.
